#!/bin/sh -x

run_app() {

    cd /opt/mozilla-iot-gateway

    echo "node version"
    node --version

    echo "npm version"
    npm --version

    echo "Starting gateway ..."
    npm start

}

run_app > /tmp/mozilla-iot-run.log 2>&1 &
